name: C/C++ CI

on:
  push:
    branches: [ homeworkOOP* ]
  pull_request:
    branches: [ homeworkOOP* ]

jobs:
  checker:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Run check.sh
      working-directory: shm
      run: |
        chmod +x check.sh
        ./shm CMakeLists.txt
